### ISSUE TITLE
Input checking for sptensor

### ISSUE THREAD

**Issue by tgkolda** [sandialabs/pyttb#113]
Hi, I created an sptensor with the argument in the wrong order (shape, subs, vals) rather than (subs, vals, shape) and received no error message.  FWIW, the same thing in MATLAB does seem to produce an error.

**Comment by ntjohnson1** [comment]
Hi Tammy. Thanks for submitting the issues! I think this might be a documentation issue, or potentially an interface one. Can you provide the reproduction steps in python and MATLAB to confirm? In python when I swapped things I did see an error, but maybe I misinterpreted your description.

# Documentation side:
`sptensor.from_data` in pyttb maps to `sptensor(arg_1, arg_2, arg_3, 0)` in MATLAB where `sptensor.from_aggregator` in pyttb maps to `sptensor(arg_1, arg_2, arg_3)` or `sptensor(arg_1, arg_2, arg_3, func)`.

```matlab
>> shape = [2,2];
>> subs = [1,1; 2,2];
>> vals = [1;2];
>> sptensor(shape, subs, vals, 0)
ans is a sparse tensor of size 1 x 2 with 1 nonzeros
	(2,2)     1     1
>> sptensor(shape, subs, vals)
Error using tt_valscheck
Values must be a column array

Error in sptensor (line 298)
    tt_valscheck(vals);
```

# Interface side:
Danny has brought up adding overloaded constructors for the classes to match MATLAB so users don't need to know the explicit options as directly, but it doesn't look like that has manifested in a ticket yet

**Comment by tgkolda** [comment]
Sounds good. FWIW, some of the input checking in MATLAB is skipped because it occurs automatically inside the MATLAB functions that are called. That said, you may notice that some constructors in the MATLAB toolbox have "fast" versions that skip all the error checking.

**Comment by ntjohnson1** [comment]
PR merged with updated documentation
