### ISSUE TITLE
Create files for tutorial

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#129]
Should align with structure of TTB for MATLAB docs.

- tensor: Dense tensors, extending MATLAB's native mutlidimensional array capabilities.
- sptensor: Sparse tensors, only stores the nonzeros and their indices.
- symtensor: Symmetric tensor, only stores the unique entries.
- ttensor: Tucker decomposed tensor, stored as a core and factor matrices.
- ktensor: Kruskal decomposed tensor, stored as weight and factor matrices.
- symktensor: Kruskal decomposed symmetric tensor, stored as weight and factor matrix.
- sumtensor: Sum of different types of tensors, never formed explicitly.

- cp_als - Alternating least squares (ALS) method, the gold standard
- cp_apr - Alternating Poisson regression (APR) using KL-divergence fitting function for Poisson tensor decomposition

- hosvd - Higher-order SVD (HOSVD), including sequentially-truncated HOSVD
- tucker_als - Higher-order orthogonal iteration

- Multiplying Tensors - Covers many types of tensor multiplication including ttv, ttm, ttt, mttkrp, innerprod, contract, norm
- Mode-n Vectors - Generating the leading mode-n vectors using nvecs
- Collapsing and Scaling Tensors - Computing sums, means, mins, maxs, and so on for portions of the tensor and conversely scaling portions of the tensor.
- Converting Between Tensors and Matrices - Convert between tensors and matrices, both dense and sparse.
- Creating Test Problems - Covers create_problem and create_guess for generating test random problems with specified characteristics
- Identities - Exploration of identities and connections among tensor and matrix operations
- Importing and Exporting Tensor Data - Covers import_data and export_data for reading and writing tensor, sptensor, and ktensor objects

**Comment by tgkolda** [comment]
Hi Danny, I'm having trouble with the "collapse" function. Can you add documentation for that too? Many thanks!

**Comment by dmdunla** [comment]
Can you let me know how you are looking at documentation? Through `help(ttb.tensor.collapse)`, through `pydoc`, through looking at code, etc. We are working on docs, and this will be helpful to know.

Also, can you provide an example of what you are trying to `collapse`? If you provide some code that creates a `tensor` (or `sptensor`, etc.) that you are trying to `collapse`, that would be helpful to see.
From: Tammy Kolda ***@***.***>
Date: Monday, June 5, 2023 at 10:09 AM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Daniel M ***@***.***>, Assign ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] Create files for tutorial (Issue #129)

Hi Danny, I'm having trouble with the "collapse" function. Can you add documentation for that too? Many thanks!

**Comment by tgkolda** [comment]
I guess I was looking at the source code. I just looked at https://pyttb.readthedocs.io/en/latest/sptensor.html#pyttb.sptensor.sptensor as was perhaps more confused about the inputs and outputs. One main problem is that collapse didn't have any example with less than all the modes collapsed, and I didn't realize that the input had to by a numpy array.

**Comment by dmdunla** [comment]
Other user doc Issues cover this request.
