### ISSUE TITLE
Add Versioned Documentation to RTD

### ISSUE THREAD

**Issue by ntjohnson1** [sandialabs/pyttb#141]
Read the docs supports versioned docs based on tags. I think we just need to enable it. https://docs.readthedocs.io/en/stable/versions.html not high priority but probably a nice to have if we start to make breaking changes for 2.0.0 or after.

**Comment by ntjohnson1** [comment]
Preliminary assigned to Danny since I think he's the only maintainer for RTD.

**Comment by dmdunla** [comment]
It looks like this supports semantic versioning in tags, but I have been adding `v` before the version in release tags to this point, so the tags are not picked up by default.

**Comment by dmdunla** [comment]
Do we want docs for all releases to be available? This seems like overkill.

**Comment by ntjohnson1** [comment]
I don't think it hurts anything for RTD to store the historical ones. Our changes aren't that large so maybe it's slightly overkill but zero versioning also seems suboptimal.

**Comment by ntjohnson1** [comment]
It looks like there are some options to hide exceptionally old docs https://docs.readthedocs.io/en/stable/versions.html#hidden if just the total number is the concern

**Comment by dmdunla** [comment]
I activated docs for all releases, but hid all but the latest {MAJOR}.{MINOR} releases. Those will show up in the flyout menu.
