### ISSUE TITLE
Align sptensor tutorial with python version

### ISSUE THREAD

**Issue by DeepBlockDeepak** [sandialabs/pyttb#151]
Goal: Replicate the [TTB sptensor](https://tensortoolbox.org/sptensor_doc.html) doc within pyttb/tutorial ipynb file, similar to the Tensors.ipynb file in tutorial/.

**Comment by DeepBlockDeepak** [comment]
## TODO List in Sptensors.ipynb 
---
### 1. SQUASH Method
**Section**: 'Use squash to remove empty slices from a Sptensor'

**Issue**: The `ttb.sptensor` class does not have a `squash` method yet implemented. 


---

### 2. Extracting Nested Item 
**Section**: 'Subscripted reference for a Sptensor'

**Issue**: Uncertainty on how to extract a nested tensor element from a 2D array input.

**Description**: TODO : Use `.item()` to extract the nested item here? Not sure how to get extraction to work with a 2D(?) array as input, like in the MATLAB version. 

Ex:
```python
>>> X[1,1,1]
array([[0]])
```

However, in [MATLAB ttb](https://tensortoolbox.org/sptensor_doc.html#28:~:text=X(1%2C2%2C1),ans%20%3D%0A%0A%20%20%20%20%200) it looks like:
```matlab
X(1,2,1) %<-- Extract the (1,2,1) element, which is zero.
ans =

     0
```


---

### 3. Error-Prone 'extract' 
**Section**: 'Subscripted reference for a Sptensor'

**Issue**: `'extract'` functionality is not working as expected.

**Description**: `'extract'` seems to be error-prone. However, it is known that `'extract'` is under ongoing development. See [here](https://gitlab.com/tensors/tensor_toolbox/-/issues/73).

---

### 4. ValueError in Assigning a Subtensor
**Section**: 'Subscripted assignment for a Sptensor'

**Issue**: ValueError in attempting to assign a subtensor.

**Description**: Currently producing ValueError in attempting to assign a subtensor. The following snippet produces a ValueError:
```python
>>> np.random.seed(0)
>>> X = ttb.sptensor.from_data(np.array([[]]), np.array([[]]), (30, 40, 20))
>>> Y = ttb.sptenrand((10, 10, 10), nonzeros = 10)
>>> X[10:20, 10:20, 10:20] = Y # Assign a subtensor.
.
.
.

ValueError: could not broadcast input array from shape (0,) into shape (10,)
```

---

### 5. Uncertainty on 'end()' usage 
**Section**: 'Use end as the last index'

**Issue**: Not sure how to implement 'end()' in a way analogous to MATLAB.

**Description**: How can we implement 'end()' in the way seen in the ttb page:
```matlab
X(end-10:end,end-10:end,end-5:end)  %<-- Same as X(108:118,110:120,115:120)
```
---

**Comment by ntjohnson1** [comment]
1. Squash appears to be new as of 3 months ago (I guess you could file a ticket and say squash isn't supported yet).
2. Can you open a singular ticket for sptensor indexing issues identified in your tutorial? I think this is a bug on my part and I am not squeezing single entries
3. What do you mean by ` functionality is not working as expected.` Currently `extract` has no impact. If you are seeing some other bug more detail added to the sptensor indexing ticket would be useful.
4. This looks like it should also go in the indexing bug as another example we aren't supporting properly.
5. Hmm I thought Danny mentioned it on the first tutorial. Python has negative indexing (I don't know if I've tested that it actually works correctly on pyttb) so we shouldn't need `end` usage in slices. `X[-10:, -10:, -5]` would be the pythonic way to write the slice above (pending off by 1 errors)
