### ISSUE TITLE
Linking back to Tensor Toolbox for MATLAB

### ISSUE THREAD

**Issue by tgkolda** [sandialabs/pyttb#154]
I'm not sure it says in any obvious place that pyttb is closely related to Tensor Toolbox for MATLAB and mirrors it fairly directly. I think this package would gain a lot by emphasizing the connection. Many of the issues assume this knowledge of the mirroring implicitly, but I expect anyone else would be pretty confused! Moreover, it might bring a lot of users who are already familiar with the MATLAB Toolbox. Even just from a search-engine optimization perspective, this will help more people to find this software.

**Comment by dmdunla** [comment]
Closed with 1085e1ef20a9d8ea44400b9e41d1fc5b8996329d
