### ISSUE TITLE
tensor/sptensor: `__getitem__()` determine use of `extract` parameter 

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#160]
The following, 
- `pyttb.tensor.__getitem__`
- `pyttb.sptensor.__getitem__`

can take a parameter, `extract`, as input in the corresponding TTB for MATLAB.

I suggest we remove this functionality, as it has caused several challenges in the implementation. Moreover, I believe that a second step of converting the output of `__getitem__` to a vector when needed would suffice for the intended use case.

[TTB MATLAB Isssue 73](https://gitlab.com/tensors/tensor_toolbox/-/issues/73) plans to update the docs to reflect the intended use there: for 1-way tensor/sptensor objects, the `extract` is used to request that the output should be a vector not a tensor/subtensor.

**Comment by ntjohnson1** [comment]
I support dropping extract. It looks like we never really supported it in sptensor anyway.

**Comment by DeepBlockDeepak** [comment]
Checkpoint issue #171 will continue this work.
