### ISSUE TITLE
ktensor datadisp method missing

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#166]
Tensor Toolbox for MATLAB uses `ktensor/datadisp` to output the data is a particular format:

```matlab
>> X = ktensor({[0.8 0.1 1e-10]',[1e-5 2 3 1e-4]',[0.5 0.5]'}); %<-- Create tensor.
>> X = arrange(X) %<-- Normalize the factors.
>> labelsDim1 = {'one','two','three'}; %<-- Labels for mode 1.
>> labelsDim2 = {'A','B','C','D'}; %<-- Labels for mode 2.
>> labelsDim3 = {'on','off'}; %<-- Labels for mode 3.
>> datadisp(X,{labelsDim1,labelsDim2,labelsDim3}) %<-- Display.

======== Group 1 ========

Weight = 2.055480
Score      Id   Name
 0.9922779     1 one
 0.1240347     2 two
Score      Id   Name
 0.8320503     3 C
 0.5547002     2 B
 2.774e-05     4 D
 2.774e-06     1 A
Score      Id   Name
 0.7071068     1 on
 0.7071068     2 off

```

Do we want to replicate this functionality? I am unsure how useful it is.

**Comment by tgkolda** [comment]
I didn't even know the MATLAB TTB had such functionality! Not important IMHO.

**Comment by dmdunla** [comment]
Haha, a quote for the ages …

From: Tammy Kolda ***@***.***>
Date: Friday, June 30, 2023 at 12:42 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Daniel M ***@***.***>, Author ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] ktensor datadisp method missing (Issue #166)

I didn't even know the MATLAB TTB had such functionality! Not important IMHO.

**Comment by dmdunla** [comment]
Not really used in TTB for MATLAB, so closing as answered. We will not implement `ktensor.datadisp` unless requested in the future.
