### ISSUE TITLE
Complete tutorial: `ktensor`

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#168]
There are some TODO's listed in `tutorial/class_ktensor.ipynb` tutorial. The following issues should be closed before this issue can be closed:

- #61 
- #161
- #165
- #166 
- #167 

Once the above issues are closed, update the corresponding unfinished examples in `tutorial/class_ktensor.ipynb`

**Comment by ntjohnson1** [comment]
Note for `full` not working as expected please refer to the ticket that has been closed. Pyttb doesn't have a bug but rather there is a bug in the tutorial that should be resolved.
