### ISSUE TITLE
Implement squash() for class `sptensor`

### ISSUE THREAD

**Issue by DeepBlockDeepak** [sandialabs/pyttb#169]
The TTB Sparse Tensor [has a squash method](https://www.tensortoolbox.org/sptensor_doc.html#:~:text=from%20a%20sptensor-,Use%20squash%20to%20remove%20empty%20slices%20from%20a%20sptensor,-Use%20full%20or) which isn't implemented yet in pyttb's sptensor class.

**Comment by DeepBlockDeepak** [comment]
Checkpoint issue #171 will continue this work.

**Comment by ntjohnson1** [comment]
Looks like it was added just in a single commit with tests. https://gitlab.com/tensors/tensor_toolbox/-/commit/9b80c8884ec22d93ae3bf85875039211ba19312d
