### ISSUE TITLE
Implement `__getitem__` for `ttensor`

### ISSUE THREAD

**Issue by DeepBlockDeepak** [sandialabs/pyttb#172]
`__getitem__()` needs to be implemented for the ttensor class.

```python
>>> import pyttb as ttb
>>> import numpy as np
>>> np.random.seed(0)
>>> core = ttb.tensor.from_data(np.random.rand(3,2,1), shape=(3,2,1)) # The core tensor.
>>> U = [np.random.rand(5,3), np.random.rand(4,2), np.random.rand(3,1)] # The factor matrices.
>>> X = ttb.ttensor.from_data(core, U) # Create the ttensor.
>>> X[1] # No __getitem__()

TypeError: 'ttensor' object is not subscriptable
```

**Comment by ntjohnson1** [comment]
Looking at the MATLAB documentation `X[index]` is simply a shorthand for `X.u[index]`. My vote would be to avoid the redundancy and require the explicit indexing into either `X.core` or `X.u`. Making this same decision for `ktensor` should also resolve https://github.com/sandialabs/pyttb/issues/165. In general if we can have one an only one way to do the right thing that's preferable.

CC: @dmdunla for thoughts

**Comment by dmdunla** [comment]
I do not see `X(index)` working in MATLAB. It does provide `X{index}`, but we are not using cell arrays in `pyttb`. 

Thus, I agree with Nick that we should not support indices into a `ttensor`, just support indexing into the core and individual factor matrices.
