### ISSUE TITLE
Create mapping of pyttb-TTB functionality

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#180]
To assist transitions from the Tensor Toolbox for MATLAB to pyttb, create some reference documentation of the mapping of methods and any important differences.

**Comment by ntjohnson1** [comment]
I believe https://github.com/sandialabs/pyttb/wiki/Development-Plans already has moderate coverage here (in case this wasn't already what you were thinking about).

**Comment by dmdunla** [comment]
Yes, I was going to start from there (which is incomplete) and then consider moving it to RTD as a new section.

We're past the original intent of dev plans, but this will provide the basis for the MATLAB->pyttb mappings.

**Comment by dmdunla** [comment]
This is related to:

- #110

As part of the RTD docs, I suggest we add a subsection of Getting Started called, "pyttb for MATLAB Users"

**Comment by ntjohnson1** [comment]
I saw @jeremy-myers started to work on this already by writing up tables in restructured text (which looks great so far!). I would really like something that fails loudly when we continue to updated pyttb and potentially diverge from the MATLAB. We could probably setup the MATLAB getting started stuff as Jupyter notebooks rendered to our read the docs as well. Then if we change and interface that breaks it won't be allowed to check in. There are probably other ways.

Alternatively I think we can just add doctests to sphinx/RST if we think that would be easier. I'm not sure if the ability to interact with a jupyter notebook is as relevant for users coming from MATLAB.

**Comment by jeremy-myers** [comment]
I've been quiet the last few weeks but expect to see some commits ones this PR this upcoming week.

**Comment by ntjohnson1** [comment]
Zero rush on my side. I was on a variety of flights this week so I was much more active. Just wanted to weigh in to reduce a large refactor after this was 100% complete.

**Comment by dmdunla** [comment]
Closed with 42f12892bae58bea3bf6a37a8dd12f31da2f0ec5
