### ISSUE TITLE
Testing: use `np.array_equal()` instead of `(==).all()`

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#185]
**Suggestion:** In testing, use `np.array_equal()` instead of `(==).all()` for better readability. Nick also uncovered a bug in the past using this approach that was not covered by `all()`.

**Comment by ntjohnson1** [comment]
Re-found an example of the bug:

```python
>>> import numpy as np
>>> ((2,2) == np.ones((2,2)) * 2).all()
True
>>> np.array_equal(np.ones((2,2))*2, (2,2))
False

**Comment by dmdunla** [comment]
Yes, I see that. Is this a result of numpy broadcasting in `__eq__`?

```python
>>> import numpy as np
>>> (2,3) == np.ones((2,2)) * 2
array([[ True, False],
       [ True, False]])
```

**Comment by ntjohnson1** [comment]
I assume so. Either way array_equal is pretty obvious and clear. The example failure mode was just additional justification.
