### ISSUE TITLE
Tutorial: udpdate ktensor tutorial to reflect recent class changes

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#189]
There were major changes in
- #182 

Changes to the [ktensor tutorial](https://github.com/sandialabs/pyttb/blob/main/docs/source/tutorial/class_ktensor.ipynb) are now required to reflect these changes.

@ntjohnson1 Do you know why this was not caught by your recent inclusion of PR-driven RTD builds (#178)?

**Comment by ntjohnson1** [comment]
Hmm in the preview for your PR we do see the error in the generated doc https://pyttb--182.org.readthedocs.build/en/182/tutorial/class_ktensor.html. My assumption is that there is a configuration to lead to this being a build error that I missed.

**Comment by dmdunla** [comment]
Ah user that now. I was expecting it to error out if the docs build failed.
________________________________
From: Nick ***@***.***>
Sent: Friday, July 7, 2023 12:09:04 PM
To: sandialabs/pyttb ***@***.***>
Cc: Dunlavy, Daniel M ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [sandialabs/pyttb] Tutorial: udpdate ktensor tutorial to reflect recent class changes (Issue #189)


Hmm in the preview for your PR we do see the error in the generated doc https://pyttb--182.org.readthedocs.build/en/182/tutorial/class_ktensor.html. My assumption is that there is a configuration to lead to this being a build error that I missed.

**Comment by ntjohnson1** [comment]
That was my expectation as well. If you like you can file a ticket, otherwise I'll plan to take a look this weekend/next week to figure out what setting we need for it to fail on error.

**Comment by ntjohnson1** [comment]
Ok it was a one line config change. I put a draft demo here https://github.com/sandialabs/pyttb/pull/191 we should probably cherry-pick that commit into the solution that fixes the docs. In the mean time we should let it float so we aren't blocked on all PRs. https://github.com/sandialabs/pyttb/pull/191

**Comment by ntjohnson1** [comment]
Resolved in https://github.com/sandialabs/pyttb/pull/193
