### ISSUE TITLE
Tutorials section link gives 404 error

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#224]
The link to [tutorials](https://github.com/sandialabs/pyttb/tree/main/tutorial) in the [USER_RUBRIC](https://github.com/sandialabs/pyttb/blob/main/USER_RUBRIC.md#sample-code--tutorials) gives 404 page not found error. The section is also referenced in [Getting Started (for Novice Users)](https://github.com/sandialabs/pyttb/blob/main/USER_RUBRIC.md#getting-started-for-novice-users).

**Comment by ntjohnson1** [comment]
Thanks for the catch. Our tutorials moved to https://github.com/sandialabs/pyttb/tree/main/docs/source/tutorial

We should probably leverage an automated tool in our docs optional install to check these. Top result for a python package was https://github.com/scivision/linkchecker-markdown but I'll probably look a bit deeper this weekend.

**Comment by jeremy-myers** [comment]
@ntjohnson1 That's an interesting idea. I'll close this for now.

**Comment by ntjohnson1** [comment]
I was mostly just letting you know where the tutorials are in the repo. I'm reopening because even if we aren't testing the validity of the links we should update them to be correct. Thanks for reviewing the repo and submitting the issues!

**Comment by ntjohnson1** [comment]
@kshitiz305 it looks like you resolved the broken link but merged the change into your own fork instead of opening a PR for our repo. Feel free to open a PR. Otherwise I'll land a similar change this weekend.

**Comment by kshitiz305** [comment]
Hey @ntjohnson1 Please have a look at this.
