### ISSUE TITLE
Implement `threshold` for ktensor `score()`

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#225]
Ktensor member function `score()` takes a float argument `threshold`. The output variable `flag` is documented to be set based on `threshold`, but `threshold` is never checked and `flag` is never updated.

# Example
```
>>> factors = [np.ones((3,3)), np.ones((4,3)), np.ones((5,3))]
>>> weights = np.array([2.,1.,3.])
>>> K = ttb.ktensor(factors, weights)
>>> factors_2 = [np.ones((3,2)), np.ones((4,2)), np.ones((5,2))]
>>> weights_2 = np.array([2.,4.])
>>> K2 = ttb.ktensor(factors_2, weights_2)
>>> score, Kperm, flag, perm = K.score(K2) # default threshold is 0.99
>>> print(score)
0.875
>>> print(flag) # should return False
True 
>>> score, Kperm, flag, perm = K.score(K2,threshold=0.88)
>>> print(flag) # should return False
True
```

# Other fixes
* Numerical guard on `threshold` values
```
K.score(K2,threshold=1.8)
```
should throw an error. Since `threshold` should be <1.

# Differences from MATLAB Tensor Toolbox
* In MATLAB TTB, default threshold is 0.99^N, where N is the number of dimensions. In pyttb, it is just 0.99.

**Comment by ntjohnson1** [comment]
In pyttb we currently only have greedy matching enabled. Always setting the flag to True for greedy seems to be similar behavior in MATLAB so might want to open a similar ticket there. In the meantime my interpretation matches yours so I can resolve it here.
