### ISSUE TITLE
Tensor member function `scale()` not found

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#226]
Following the documentation in `ttb.tensor` for `scale()`:
```
>>> T = ttb.tenones((3, 4, 5))
>>> S = np.arange(5)
>>> Y = T.scale(S, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tensor' object has no attribute 'scale'. Did you mean: 'shape'?
```

**Comment by dmdunla** [comment]
This was updated with a PR yesterday. Can you pull and verify this is still an issue or not?

________________________________
From: Jeremy Myers ***@***.***>
Sent: Wednesday, September 6, 2023 4:57:47 PM
To: sandialabs/pyttb ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [EXTERNAL] [sandialabs/pyttb] Tensor member function `scale()` (Issue #226)


Following the documentation in ttb.tensor for scale():

>>> T = ttb.tenones((3, 4, 5))
>>> S = np.arange(5)
>>> Y = T.scale(S, 2)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'tensor' object has no attribute 'scale'. Did you mean: 'shape'?

**Comment by jeremy-myers** [comment]
It works. Closing issue.
