### ISSUE TITLE
Using matplotlib plots in tutorials breaks the CI regressions

### ISSUE THREAD

**Issue by jeremy-myers** [sandialabs/pyttb#275]
There are various TODOs in tutorial notebooks as placeholders for calls to matplotlib. However, these break CI regressions.

**Comment by ntjohnson1** [comment]
Can you add more details and examples here? Does the readthedocs preview fail or our pytest suite? Do the same things pass locally and it's only an issue with the automation? There were a bunch of tutorial PRs that merged and it wasn't immediately obvious which have this issue

**Comment by jeremy-myers** [comment]
@ntjohnson1 To do so, I'll need to create a PR for a tutorial that uses matplotlib to gather that information. Once we have the solution, it can then be deleted.

**Comment by jeremy-myers** [comment]
@ntjohnson1 It fails on the RTD build: `ModuleNotFoundError: No module named 'matplotlib'`.

**Comment by ntjohnson1** [comment]
Ya, our dev environment didn't specify `matplotlib`. Running the doc build locally failed for me so you must have manually installed matplotlib, a newer version of some package accidentally pulled it in, or there was some environment contamination. Either way I pushed a commit to your branch that appears to have resolved the matplotlib dependency issue for our docs. You should hopefully be able to remove all the TODOs now and confirm things are ok.

Small nit: It looks like the gcp_opt and hosvd notebooks both run 2-5x slower than any of the other notebooks. Not a huge deal but if there is anything minor that comes to mind that reduces the runtime without hurting the instructional nature would be nice. The overall time isn't sluggish yet, but things to gradually slow over time so good to be proactive.

**Comment by jeremy-myers** [comment]
Thanks @ntjohnson1! I'll run on my end and clear up the TODOs.

Re: `gcp_opt` and `hosvd`. I'll look into it. I too noticed they run slowly. Maybe @dmdunla has some ideas...

**Comment by ntjohnson1** [comment]
On my ~6 year old laptop they take 15s each and I don't run the tutorial build in my usual dev iteration loop. So I'd say its low priority. I just figured if there was an iteration count or tensor size we could easily decrease without hurting the demo its a nice to have while we are familiar with the context. Otherwise we can punt on it until it becomes an issue.

**Comment by jeremy-myers** [comment]
Closing this issue as the original issue was resolved.
