### ISSUE TITLE
Fix Heading Levels in Tutorials

### ISSUE THREAD

**Issue by ntjohnson1** [sandialabs/pyttb#277]
We should only have 1 top level heading for every tutorial `#` everything else should be a sub-heading `##`, `###`, .. etc. See the tutorials landing page where it gives a preview of the nested heading structure https://pyttb.readthedocs.io/en/latest/tutorials.html on a quick glance it looks like cp_als, and hosvd have this issue.

Should be a fairly small change so might be nice to wrap up while you are working on the matplotlib fixes.

**Comment by jeremy-myers** [comment]
This will be resolved by PR https://github.com/sandialabs/pyttb/pull/276

**Comment by ntjohnson1** [comment]
Resolved in #276
