### ISSUE TITLE
ktensor no longer provides from_data()

### ISSUE THREAD

**Issue by ghbrown** [sandialabs/pyttb#298]
Although the [API docs](https://pyttb.readthedocs.io/en/stable/ktensor.html) and the [linked "source code"](https://pyttb.readthedocs.io/en/stable/_modules/pyttb/ktensor.html#ktensor) suggest that ktensor has method `from_data()`, it does not.

See the latest version of [`ktensor.py`](https://github.com/sandialabs/pyttb/blob/main/pyttb/ktensor.py).

**Comment by ntjohnson1** [comment]
If I understand correctly you're pointing out a mismatch between the docs and main. You appear to be looking at the stable version of the docs which corresponds to our last release.

The version tagged latest should align to main. https://pyttb.readthedocs.io/en/latest/ktensor.html

We're trying to cut a new release from main soon, which should also help to avoid some confusion in the future.

**Comment by ghbrown** [comment]
I see, thanks for clarifying.
