### ISSUE TITLE
Add vis method to ktensor?

### ISSUE THREAD

**Issue by ghbrown** [sandialabs/pyttb#304]
I propose adding the `.vis()` method to the `ktensor` class.
As described by a colleague, this is one of the "killer features" of the MATLAB Tensor Toolbox and has no analog in pyttb.

A first draft implementation largely mirroring the [MATLAB version](https://gitlab.com/tensors/tensor_toolbox/-/blob/dev/@ktensor/viz.m?ref_type=heads) is started in #301.

**Comment by dmdunla** [comment]
Closed with 4991021935c3e281cd5397eac00917b3b4b92ef4

**Comment by ghbrown** [comment]
@dmdunla Thanks for pushing this through the pipeline!
(Same goes for the other PRs as well.)
