### ISSUE TITLE
Tutorial needs to be ordered

### ISSUE THREAD

**Issue by tgkolda** [sandialabs/pyttb#342]
The tutorial in MATLAB are ordered and have a hierarchy. Here is the top level:

![image](https://github.com/user-attachments/assets/8ad3aa17-332f-4e2a-aad7-80e75b326b4e)

The tutorial in pyttb are not ordered (and there are two levels in the heirarchy called "tutorials"). It makes it hard for a user to know where to start. 

![image](https://github.com/user-attachments/assets/ffb39094-b585-49b6-952a-21c387573714)

**Comment by ntjohnson1** [comment]
Thanks for catching this. Looks much nicer with the hierarchy.

**Comment by tgkolda** [comment]
Awesome!
