### ISSUE TITLE
Bug in CP-APR documentation

### ISSUE THREAD

**Issue by tgkolda** [sandialabs/pyttb#364]
https://pyttb.readthedocs.io/en/latest/tutorial/algorithm_cp_apr.html

This error is printed repeatedly: `WARNING:root:Selected no copy, but input data isn't F ordered so must copy.`

**Comment by ntjohnson1** [comment]
This is a good catch and a more global issue to resolve on the documentation. I opened #368 to track it globally, so I will close this but it will get resolved when we fix it everywhere.
