### ISSUE TITLE
Support general cores in TTENSOR

### ISSUE THREAD

**Issue by ntjohnson1** [sandialabs/pyttb#61]
[This ](https://github.com/sandialabs/pyttb/pull/51) added ttensor support for dense cores. MATLAB supports any core that follows an interface. We can probably use protocols and mypy to sanity check this. Alternatively may consider creating a base class for some shared pyttb tensor functionality.

**Comment by DeepBlockDeepak** [comment]
Leaving note here to highlight issue #147 's `Core Type Conversion` note, and Nick's response to it. The Ktensor.ipynb will need to be updated accordingly, once this this `core` issue is resolved.

**Comment by ntjohnson1** [comment]
MATLAB states generic cores are supported but special cases tensors and sptensor. For the scope of this ticket only adding support to sptensor.
