### ISSUE TITLE
Address ttm dims=0 ambiguity

### ISSUE THREAD

**Issue by ntjohnson1** [sandialabs/pyttb#62]
Identified here https://github.com/sandialabs/pyttb/pull/53 MATLAB is 1 indexed so -index represents all indices EXCEPT for the one listed. However since python is 0 index -0 is the same as 0 so there is an ambiguity. One proposal is `tensor.ttm(dims=None, exclude_dims=None)`. Would need to see if this ambiguity is the same throughout other tensor implementations and should be updated uniformly/checked in algorithms that use the tensors.

**Comment by ntjohnson1** [comment]
It looks like tt_dimscheck is also implicitly 1 indexed for our negative dims so we probably need to actually update this interface deeper where negative indices are used.

**Comment by dmdunla** [comment]
> Identified here #53 MATLAB is 1 indexed so -index represents all indices EXCEPT for the one listed. However since python is 0 index -0 is the same as 0 so there is an ambiguity. One proposal is `tensor.ttm(dims=None, exclude_dims=None)`. Would need to see if this ambiguity is the same throughout other tensor implementations and should be updated uniformly/checked in algorithms that use the tensors.

I like the proposed change to use `tensor.ttm(dims=None, exclude_dims=None)`

This will require changes to (at least)
- [ ] `pyttb_utils.tt_dimscheck`
- [ ] `sptensor.ttm`
- [ ] `tensor.ttm`
- [ ] `ttensor.ttm`

**Comment by ntjohnson1** [comment]
PR merged that resolved tt_dimscheck, as well as its usage in ttm, ttv, and ttsv
