### ISSUE TITLE
Implement teneye

### ISSUE THREAD

**Issue by dmdunla** [sandialabs/pyttb#72]
Create tensor with ones on the superdiagonal

**Comment by DeepBlockDeepak** [comment]
Check out `tendiag()`

**Comment by dmdunla** [comment]
@DeepBlockDeepak Sorry, I was mistaken about this issue. I now see what teneye is and it is very different than tendiag. I suggest you switch to another "good first issue" for now. I'll think more about this issue and take a look at it myself.

**Comment by dmdunla** [comment]
Closed with #222
